# The mode is set to AWS. You may want to change this is running locally
php-fpm:
  image: 791778434480.dkr.ecr.us-east-1.amazonaws.com/openbridge/php-fpm:latest
  volumes:
    - /ebs:/ebs
  environment:
    - ob_mode=aws
    - ob_tag=php-fpm
  ports:
    - "9000:9000"
  restart: always
  tty: true
  container_name: php-fpm
  ulimits:
    nproc: 65535
    nofile:
        soft: 49999
        hard: 99999
