version: '3.1'
services:
  php-fpm:
    image: openbridge/php-fpm
    container_name: php-fpm
    restart: always
    tty: true
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
